name: Provision Resources 

on: #trigger
  pull_request:
    branches:
      - main
    types: [ closed ] 

jobs:
  merge_job:
    if: github.event.pull_request.merged == true   
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply -var "aws_credentials=$AWS_CREDENTIALS" --auto-approve
